### PR TITLE
SSN regex and tests added

### LINKED ISSUE #79: Create regex to detect SSN

### PR DESCRIPTION
**Pull request by alexisc0305**
Created regex to detect SSNs and tests to check for valid/invalid SSNs.
Closes #79

### CODE REVIEW

**Review by claesmk — APPROVED** [review]
Your regex works fine so I'll approve the PR, however, you could consider simplifying like this:
```
\d{3}-\d{2}-\d{4}
```

**Comment by alexisc0305** [comment]
Thank you for your feedback! I was initially going to use that regex, but I read online that '000-00-0000' does not qualify as a valid SSN. Do you think there is a simpler regex that can be used while accounting for this edge case?

**Comment by claesmk** [comment]
OK, I didn't realize you were trying to check for SSN validity, which is actually more complicated because there are a range of numbers which are actually invalid. 

Usually the more complicated you make a regex, the more likely it is to fail in ways you least expect.

If I had a requirement to match something which looked like an SSN but not 000-00-0000 I'd probably put in special handling
```
    m = re.search(r'(\d{3})-(\d{2})-(\d{4})', text)
    if m:
        print(m.groups())
        if m.groups() == ('000', '00', '0000'):
            return False
        return True
    return False
```
Note that by using 3 match groups instead of one, this allows you to potentially add range checks for each of the area, group, and serial numbers as defined by the SSA

**Comment by alexisc0305** [comment]
> OK, I didn't realize you were trying to check for SSN validity, which is actually more complicated because there are a range of numbers which are actually invalid.
> 
> Usually the more complicated you make a regex, the more likely it is to fail in ways you least expect.
> 
> If I had a requirement to match something which looked like an SSN but not 000-00-0000 I'd probably put in special handling
> 
> ```
>     m = re.search(r'(\d{3})-(\d{2})-(\d{4})', text)
>     if m:
>         print(m.groups())
>         if m.groups() == ('000', '00', '0000'):
>             return False
>         return True
>     return False
> ```
> 
> Note that by using 3 match groups instead of one, this allows you to potentially add range checks for each of the area, group, and serial numbers as defined by the SSA

That makes a lot of sense; thank you for clarifying!

**Pull request merged**
