### PR TITLE
Clean up on team 4 scan file

### PR DESCRIPTION
**Pull request by nigeltiany**

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
You have a[ test case](https://github.com/NCATComp410/comp410_summer_2022/runs/7664935150?check_suite_focus=true) failing

**Comment by nigeltiany** [comment]
@claesmk The changes causing a failure were not introduced by this PR or the one recently merged.

**Comment by claesmk** [comment]
@nigeltiany the change that actually caused the unit test to fail was [this](https://github.com/NCATComp410/comp410_summer_2022/commit/f5792a9c5c64eafeb33b94a2438ec57d7baf72aa) - removing the ^ and $ from find_account_number caused the failure.

**Review by claesmk — APPROVED** [review]
It looks like you are detecting the types of pii that your team implemented.

**Pull request merged**
